{% set name = "spherical_functions" %}
{% set pypiname = "spherical-functions" %}
{% set version = "2023.0.0" %}
{% set sha256 = "6db7e5fac8289ec767ae75c780b7d193f6a8b88d74cf14a79d568bb8dda3f4bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - numba
    - quaternion
    - spinsfast

test:
  requires:
    - python {{ python_min }}
  imports:
    - spherical_functions

about:
  home: http://github.com/moble/spherical_functions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python/numba implementation of Wigner D Matrices, spin-weighted spherical harmonics, and associated functions
  description: |
    Python/numba package for evaluating and transforming Wigner’s 𝔇 matrices, Wigner’s 3-j symbols,
    and spin-weighted (and scalar) spherical harmonics. These functions are evaluated directly in
    terms of quaternions, as well as in the more standard forms of spherical coordinates and Euler
    angles.
  dev_url: https://github.com/moble/spherical_functions

extra:
  recipe-maintainers:
    - moble
